name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 18
      uses: actions/setup-java@v1
      with:
        java-version: 18
    - name: Build with Maven
      run: mvn -B package --file HW1/tqs-hw1-102885/pom.xml
    - name: Run tests
      run: mvn test -Dtest=!pt.ua.tqsenv.integration.F_FunctionalWeb_IntegrationTest --file HW1/tqs-hw1-102885/pom.xml

